### ISSUE TITLE
Force UTF-8 encode?

### ISSUE THREAD

**Issue by Synchro** [cardinalby/phpContentDisposition#2]
I have a filename with a `Ø` character in on a page that's all UTF-8. This package sees that as valid ISO-8859-1, and so does not generate a `filename*` field. Unfortunately the browser then downloads the file with `Ã` in place of the `Ø`.

Is there some way to force the generation of a UTF-8 `filename*` field, or do you think I have a different issue?

**Comment by cardinalby** [comment]
Hi, and thanks for creating the issue!

As I found, `Ø` (capital O with stroke) is a valid ISO-8859-1 character (https://kb.iu.edu/d/aepu, code 216). I need to try to reproduce the problem, because at the moment it seems to be valid behaviour of the library, maybe something on the browser (web page encoding) side?

I have prepared a test located at [tests/browser_download](https://github.com/cardinalby/phpContentDisposition/tree/master/tests/browser_download) to check browser behaviour with `Ø` character and couldn't find any anomalies (Chrome, Safari, macOS). If you can provide a small reproducible example, I will look at it and decide how to handle this behavior.

I have just updated the library (version `1.1.0`). Now you can force the generation of UTF-8 filename* in 2 ways:

1. Pass a different `$fallback`:
```php
ContentDisposition::createAttachment("Ø.pdf", 'download.pdf')->format()
// attachment; filename="download.pdf"; filename*=UTF-8''%C3%98.pdf
```

2. Pass `$fallback === null`:
```php
ContentDisposition::createAttachment("Ø.pdf", null)->format()
// attachment; filename*=UTF-8''%C3%98.pdf
```

**Comment by Synchro** [comment]
That didn't work as it just results in a URL-encoded filename in the download. I did however track down a solution. My code generates a PDF and downloads it through a Laravel stream, and setting the charset in the content-type header fixed it:

```php
$filename = 'Filename with a Ø in.pdf';
            $fn = ContentDisposition::createAttachment($filename)->format();
            return response()->stream(
                function () use ($html) {
                    echo Browsershot::html($html)
                        ->windowSize(1280, 1024)
                        ->scale(0.5)
                        ->format('A4')
                        ->margins(10, 10, 10, 10)
                        ->showBackground()
                        ->emulateMedia('print')
                        ->timeout(120)
                        ->pdf();
                },
                200,
                [
                    //Adding charset here fixed it:
                    'Content-Type'        => 'application/pdf; charset=utf-8',
                    'Content-Disposition' => $fn
                ]
            );
```

Thanks for your help!
